"""create patch and vote tables

Revision ID: 098acda58edc
Revises: 990be6cb33a8
Create Date: 2026-07-17 21:22:46.076533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '098acda58edc'
down_revision: Union[str, Sequence[str], None] = '990be6cb33a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patch_author_id'), 'patch', ['author_id'], unique=False)
    op.create_table('vote',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patch_id', sa.Uuid(), nullable=False),
    sa.Column('voter_id', sa.Uuid(), nullable=False),
    sa.Column('choice', sa.String(length=10), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['patch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patch_id', 'voter_id', name='uq_patch_voter')
    )
    op.create_index(op.f('ix_vote_patch_id'), 'vote', ['patch_id'], unique=False)
    op.create_index(op.f('ix_vote_voter_id'), 'vote', ['voter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_voter_id'), table_name='vote')
    op.drop_index(op.f('ix_vote_patch_id'), table_name='vote')
    op.drop_table('vote')
    op.drop_index(op.f('ix_patch_author_id'), table_name='patch')
    op.drop_table('patch')
    # ### end Alembic commands ###
