"""add voting_ends_at to patch

Revision ID: 7c4832cace43
Revises: 098acda58edc
Create Date: 2026-07-17 22:31:49.197801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c4832cace43'
down_revision: Union[str, Sequence[str], None] = '098acda58edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patch', sa.Column('voting_ends_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patch', 'voting_ends_at')
    # ### end Alembic commands ###
