"""add replying_id to content

Revision ID: 990be6cb33a8
Revises: e41414fda33e
Create Date: 2026-07-17 18:26:25.764644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990be6cb33a8'
down_revision: Union[str, Sequence[str], None] = 'e41414fda33e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('replying_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_content_replying_id'), 'content', ['replying_id'], unique=False)
    op.create_foreign_key(None, 'content', 'content', ['replying_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_index(op.f('ix_content_replying_id'), table_name='content')
    op.drop_column('content', 'replying_id')
    # ### end Alembic commands ###
