"""add guilds

Revision ID: a1b2c3d4e5f6
Revises: 5dd542e97033
Create Date: 2026-07-19 22:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '5dd542e97033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=80), nullable=False),
        sa.Column('logo', sa.String(length=500), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('president_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['president_id'], ['user.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table('guild_member',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('guild_id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False, server_default='member'),
        sa.Column('joined_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('guild_id', 'user_id', name='uq_guild_user'),
    )
    op.create_index(op.f('ix_guild_member_guild_id'), 'guild_member', ['guild_id'])
    op.create_index(op.f('ix_guild_member_user_id'), 'guild_member', ['user_id'])
    op.add_column('content', sa.Column('guild_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_content_guild_id'), 'content', ['guild_id'])
    op.create_foreign_key(
        op.f('fk_content_guild_id'), 'content', 'guild',
        ['guild_id'], ['id'], ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(op.f('fk_content_guild_id'), 'content', type_='foreignkey')
    op.drop_index(op.f('ix_content_guild_id'), table_name='content')
    op.drop_column('content', 'guild_id')
    op.drop_index(op.f('ix_guild_member_user_id'), table_name='guild_member')
    op.drop_index(op.f('ix_guild_member_guild_id'), table_name='guild_member')
    op.drop_table('guild_member')
    op.drop_table('guild')
